src/NWonline/KB/urls.py
###############################################################################
# File: NWonline/KB/urls.py
# Author: Lukas Batteau
# Description: Url patterns file for the KB app
# 
# CHANGE HISTORY
# 20101209    Lukas Batteau        Added header. Removed unused import.
# 20110414    Lukas Batteau        Static path changed. Fixed redirect.
###############################################################################
from NWonline import settings
from django.conf.urls.defaults import patterns, include
from django.views.generic.simple import redirect_to
import os

urlpatterns = patterns('',
    (r'^login/$', 'NWonline.KB.views.handleLogin'),
    (r'^logout/$', 'NWonline.KB.views.handleLogout'),
    
    (r'^leden/$', 'NWonline.KB.views.handlePersoonListFilter'),
    (r'^leden/export$', 'NWonline.KB.views.handlePersoonListExport'),
    (r'^leden/update$', 'NWonline.KB.views.handlePersoonListUpdate'),
    (r'^leden/gezin/(?P<gezinId>\d*)/*$', 'NWonline.KB.views.handleGezinDetails'),    
    (r'^leden/gezin/(?P<gezinId>\d*)/persoon/add$', 'NWonline.KB.views.handleGezinPersoonAdd'),    
    (r'^leden/gezin/add/*$', 'NWonline.KB.views.handleGezinAdd'),    
    (r'^leden/gezin/persoon/(?P<persoonId>\d*)/.*$', 'NWonline.KB.views.handlePersoonDetails'),
    
    (r'^wizard/', include('NWonline.KB.wizards.urls')),
    
    (r'^query/persoon/.*$', 'NWonline.KB.ajax.queryPersoon'),
    (r'^query/gemeente/.*$', 'NWonline.KB.ajax.queryGemeente'),
    
    (r'^add/(?P<model>.*)$', 'NWonline.KB.views.handleAddInstance'),
    
    (r'^dashboard/$', 'NWonline.KB.dashboard.handleDashboard'),
    (r'^dashboard/members$', 'NWonline.KB.dashboard.handleExportMembers'),
    (r'^dashboard/election$', 'NWonline.KB.dashboard.handleExportElection'),
    (r'^dashboard/birthdays$', 'NWonline.KB.dashboard.handleExportBirthdays'),
    (r'^dashboard/email$', 'NWonline.KB.dashboard.handleExportEmail'),
    (r'^dashboard/update$', 'NWonline.KB.dashboard.exportMembersToWebsite'),
    (r'^dashboard/progress$', 'NWonline.KB.dashboard.reportExportProgress'),
    
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': os.path.join(settings.MEDIA_ROOT, 'KB')}),
        
    (r'^$', redirect_to, {'url': 'dashboard/'}),
        
)

src/NWonline/KB/wizards/urls.py
from NWonline.KB.wizards.marry import MarryWizard, MarryForm1, MarryForm2, \
    MarryForm3, MarryForm4, MarryWizardMemberUnknown, MarryForm1MemberUnknown
from NWonline.KB.wizards.membership import MembershipWizard, MembershipForm1
from django.conf.urls.defaults import patterns

urlpatterns = patterns('',
    (r'^marry/(?P<persoonId>\d*)/$', MarryWizard([MarryForm1, MarryForm2, MarryForm3, MarryForm4])),
    (r'^marry/$', MarryWizardMemberUnknown([MarryForm1MemberUnknown, MarryForm2, MarryForm3, MarryForm4])),
    (r'^membership/gezin/(?P<gezinId>\d*)/$', MembershipWizard([MembershipForm1]), { 'is_mode_family': True }),
    (r'^membership/(?P<persoonId>\d*)/$', MembershipWizard([MembershipForm1]), { 'is_mode_family': False }),
)

src/NWonline/urls.py
###############################################################################
# File: NWonline/urls.py
# Author: Lukas Batteau
# Description: Url patterns file for the NWonline project.
# 
# CHANGE HISTORY
# 20101209    Lukas Batteau        Added header. Reorganized imports.
###############################################################################
from django.conf.urls.defaults import patterns, include
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^Ledenadministratie/', include('NWonline.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^', include('NWonline.KB.urls')),
)

src/NWonline/KB/models.py
###############################################################################
# File: NWonline/KB/models.py
# Author: Lukas Batteau
# Description: Business models, mapping directly to the data model used.
# 
# CHANGE HISTORY
# 20101209    Lukas Batteau        Added header.
# 20110118    Lukas Batteau        Added constants for GezinsRol
#                                  Moved createGezinsNaam to class Gezin
#                                  Added default "NEDERLAND" for Land 
# 20110328    Lukas Batteau        Added indexes for quick filter
# 20110329    Lukas Batteau        Reorganized persoon membership
# 20110414    Lukas Batteau        Moved membership description method to model
###############################################################################
from NWonline import settings
from django.db import models
import datetime

class GemeenteType(models.Model):
    idgemeentetype = models.AutoField(primary_key=True, db_column="idGemeenteType") # Field name made lowercase.
    txtgemeentetype = models.CharField(max_length=150, db_column="txtGemeenteType") # Field name made lowercase.

    def __unicode__(self):
        return self.txtgemeentetype

    class Meta:
        db_table = u"ledendb_gemeentetypes"

class Gemeente(models.Model):
    idgemeente = models.AutoField(primary_key=True, db_column="idGemeente") # Field name made lowercase.
    txtgemeentenaam = models.CharField("Naam", max_length=150, db_column="txtGemeenteNaam", blank=True) # Field name made lowercase.
    idgemeentetype = models.ForeignKey(GemeenteType, verbose_name="Type", db_column="idGemeenteType", blank=True, null=True) # Field name made lowercase.
    txtopmerking = models.TextField("Opmerkingen", max_length=765, db_column="txtOpmerking", blank=True, null=True) # Field name made lowercase.

    def __unicode__(self):
        return self.txtgemeentenaam

    class Meta:
        db_table = u"ledendb_gemeenten"
        ordering = ["txtgemeentenaam"]


class Geslacht(models.Model):
    idgeslacht = models.AutoField(primary_key=True, db_column="idGeslacht") # Field name made lowercase.
    txtgeslacht = models.CharField(max_length=3, db_column="txtGeslacht", blank=True) # Field name made lowercase.
    txtgeslachtlang = models.CharField(max_length=150, db_column="txtGeslachtLang", blank=True) # Field name made lowercase.
    txtaanhef = models.CharField(max_length=150, db_column="txtAanhef", blank=True) # Field name made lowercase.
    txtaanhefkort = models.CharField(max_length=150, db_column="txtAanhefKort", blank=True) # Field name made lowercase.
    txtaanhefkerk = models.CharField(max_length=135, db_column="txtAanhefKerk", blank=True) # Field name made lowercase.
    txtaanhefkerkkort = models.CharField(max_length=135, db_column="txtAanhefKerkKort", blank=True) # Field name made lowercase.

    def __unicode__(self):
        return self.txtgeslachtlang

    class Meta:
        db_table = u"ledendb_geslachten"

class Land(models.Model):
    NEDERLAND = 149
    
    idland = models.AutoField(primary_key=True, db_column="idLand") # Field name made lowercase.
    txtlandnaam = models.CharField(max_length=300, db_column="txtLandnaam", blank=True) # Field name made lowercase.

    def __unicode__(self):
        return self.txtlandnaam

    class Meta:
        db_table = u"ledendb_landen"
        ordering = ["txtlandnaam"]

class Gezin(models.Model):
    idgezin = models.AutoField(primary_key=True, db_column="idGezin") # Field name made lowercase.
    txtgezinsnaam = models.CharField("Gezin", max_length=150, db_column="txtGezinsnaam", db_index=True) # Field name made lowercase.
    txtstraatnaam = models.CharField("Straat", max_length=150, db_column="txtStraatnaam", blank=True, null=True, db_index=True) # Field name made lowercase.
    inthuisnummer = models.IntegerField("Huisnummer", db_column="intHuisnummer", blank=True, null=True) # Field name made lowercase.
    txthuisnummertoevoeging = models.CharField("Toevoeging", max_length=60, db_column="txtHuisnummerToevoeging", blank=True, null=True) # Field name made lowercase.
    txtpostcode = models.CharField("Postcode", max_length=60, db_column="txtPostcode", db_index=True, blank=True, null=True) # Field name made lowercase.
    txtplaats = models.CharField("Plaats", max_length=150, db_column="txtPlaats", db_index=True, blank=True, null=True) # Field name made lowercase.
    idland = models.ForeignKey(Land, verbose_name="Land", db_column="idLand", blank=True, null=True, default=Land.NEDERLAND) # Field name made lowercase.
    txttelefoon = models.CharField("Telefoon", max_length=75, db_column="txtTelefoon", db_index=True, blank=True, null=True) # Field name made lowercase.
    txtopmerking = models.TextField("Opmerking", max_length=765, db_column="txtOpmerking", blank=True, null=True) # Field name made lowercase.
    
    @classmethod
    def create_gezins_naam(cls, persoon):
        return ("%s, %s (%s)") % ((("%s %s") % (persoon.txtachternaam, persoon.txttussenvoegsels)).strip(),
                                                persoon.txtvoorletters.replace(" ", ""),
                                                persoon.txtroepnaam)
        
    def create_address(self):
        return ("%s %s%s" % (self.txtstraatnaam, str(self.inthuisnummer), self.txthuisnummertoevoeging)).strip()

    def __unicode__(self):
        return self.txtgezinsnaam

    class Meta:
        db_table = u"ledendb_gezinnen"

class GezinsRol(models.Model):
    GEZINSHOOFD = 1
    PARTNER = 2
    KIND = 3
    
    idgezinsrol = models.AutoField(primary_key=True, db_column="idGezinsrol") # Field name made lowercase.
    txtgezinsrol = models.CharField("Rol", max_length=150, db_column="txtGezinsrol", blank=True) # Field name made lowercase.

    def __unicode__(self):
        return self.txtgezinsrol

    class Meta:
        db_table = u"ledendb_gezinsrollen"

class Wijk(models.Model):
    idwijk = models.AutoField(primary_key=True, db_column="idWijk") # Field name made lowercase.
    txtwijknaam = models.CharField(max_length=150, db_column="txtWijkNaam") # Field name made lowercase.
    txtwijknaamkort = models.CharField(max_length=9, db_column="txtWijkNaamKort", blank=True, null=True) # Field name made lowercase.

    def __unicode__(self):
        return self.txtwijknaam

    class Meta:
        db_table = u"ledendb_wijken"

class Huiskring(models.Model):
    idhuiskring = models.AutoField(primary_key=True, db_column="idHuiskring") # Field name made lowercase.
    txthuiskringnaam = models.CharField(max_length=150, db_column="txtHuiskringNaam") # Field name made lowercase.
    idwijk = models.ForeignKey(Wijk, db_column="idWijk") # Field name made lowercase.
    txtopmerking = models.TextField(max_length=765, db_column="txtOpmerking", blank=True) # Field name made lowercase.
    txtvolgnummer = models.CharField(max_length=6, db_column="txtVolgnummer", blank=True) # Field name made lowercase.

    def __unicode__(self):
        return self.txthuiskringnaam

    class Meta:
        db_table = u"ledendb_huiskringen"

class HuiskringLidRol(models.Model):
    idhuiskringlidrol = models.AutoField(primary_key=True, db_column="idHuiskringLidrol") # Field name made lowercase.
    txthuiskringlidrol = models.CharField(max_length=150, db_column="txtHuiskringLidrol") # Field name made lowercase.

    def __unicode__(self):
        return self.txthuiskringlidrol

    class Meta:
        db_table = u"ledendb_huiskringlidrollen"

class LidmaatschapVorm(models.Model):
    DOOP = 1
    BELIJDEND = 2
    GASTLID_DOOP = 3
    GASTLID_BELIJDEND = 4
    
    idlidmaatschapvorm = models.AutoField(primary_key=True, db_column="idLidmaatschapvorm") # Field name made lowercase.
    txtlidmaatschapvorm = models.CharField(max_length=150, db_column="txtLidmaatschapvorm", blank=True) # Field name made lowercase.
    boolvoorquotum = models.BooleanField(db_column="boolVoorQuotum") # Field name made lowercase. This field type is a guess.
    txtlidmaatschapvormkort = models.CharField(max_length=150, db_column="txtLidmaatschapvormKort", blank=True) # Field name made lowercase.
    txtattestatie = models.CharField(max_length=150, db_column="txtAttestatie", blank=True, null=True) # Field name made lowercase.

    def __unicode__(self):
        return self.txtlidmaatschapvorm

    class Meta:
        db_table = u"ledendb_lidmaatschapvormen"

class LidmaatschapStatus(models.Model):
    ACTIEF = 1
    VERTROKKEN = 2
    ONTTROKKEN = 3
    OVERLEDEN = 4
    
    idlidmaatschapstatus = models.AutoField(primary_key=True, db_column="idLidmaatschapstatus") # Field name made lowercase.
    txtlidmaatschapstatus = models.CharField(max_length=150, db_column="txtLidmaatschapstatus", blank=True) # Field name made lowercase.

    def __unicode__(self):
        return self.txtlidmaatschapstatus

    class Meta:
        db_table = u"ledendb_lidmaatschapstatussen"

class Attestatie(models.Model):
    CODE_BELIJDENIS = "Belijdenis"
    CODE_KERKELIJKEGEGEVENS = "Kerkelijke gegevens"
    CODE_DOOP = "Doop"
    CODE_GEZINS = "Gezins"
    CODE_VERBLIJFS = "Verblijfs"
    
    idattestatie = models.AutoField(primary_key=True)
    txtcode = models.CharField("Code", max_length=20)
    txtbeschrijving = models.TextField("Beschrijving")

    def __unicode__(self):
        return self.txtcode

class Persoon(models.Model):
    idpersoon = models.AutoField(primary_key=True, db_column="idPersoon") # Field name made lowercase.
    idlidmaatschapvorm = models.ForeignKey(LidmaatschapVorm, verbose_name="Lidmaatschap", null=False, db_column="idLidmaatschapVorm", blank=False) # Field name made lowercase.
    idgezin = models.ForeignKey(Gezin, verbose_name="Huishouden", null=True, blank=True, db_column="idGezin") # Field name made lowercase.
    idgezinsrol = models.ForeignKey(GezinsRol, verbose_name="Rol huishouden", db_column="idGezinsRol") # Field name made lowercase.

templates/KB/wizards/marry_0.html
{% extends "KB/wizards/wizard.html" %}

{% load customtags %}

{% block content %}

<form name="form" id="form" action="." method="post">{% csrf_token %}
<div class="box widget form">
<h2>Wizard trouwen ({{ step }} van {{ step_count }})</h2>
{% block question %}
<p>Met wie gaat {{ persoonA }} trouwen?</p>
{% endblock %}

<div class="form_row">
{{ form.isNew|generate:"fixed" }}<input type="text" style="display:none" id="searchFieldB" size="30" onChange="update()"/>
</div>

<div id="persoonDetails" {% if form.errors %}style="display: none"{% endif %}>
{{ form.idpersoonB }}
<div class="form_row">{{ form.txtachternaam|generate:"fixed" }} {{ form.txttussenvoegsels|generate }} {{ form.idgeslacht|generate }}</div>
<div class="form_row">{{ form.txtroepnaam|generate:"fixed" }} {{ form.txtvoorletters|generate }}</div>
<div class="form_row">{{ form.idlidmaatschapvorm|generate:"fixed" }}</div>
</div>

<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
{{ previous_fields|safe }}
</div>

<input type="button" id="submitButton" onClick="submitForm()" value="Volgende">
</form>

<script type="text/javascript">

function submitForm() {
	$('#persoonDetails :input').removeAttr('disabled');
	document.form.submit();
}

function update() {
	var isNew = $("form input[name='{{form.isNew.html_name}}']").fieldValue();

	if (isNew == "") {
		$("#persoonDetails").hide();
		$("#submitButton").attr("disabled", true);
	} else if (isNew == 1) {
		$("#persoonDetails").show();
		$("#searchFieldB").hide();
		$("#submitButton").removeAttr('disabled');
		$('#persoonDetails :input').removeAttr('disabled');
	} else {
		$('#persoonDetails :input').attr('disabled', true);
		$("#persoonDetails").show();
		$("#searchFieldB").show().focus();
		if (!$("#id_{{ form.idpersoonB.html_name }}").val()) {
			$("#submitButton").attr("disabled", true);
		} else {
			$("#submitButton").removeAttr('disabled');
		}
	}	
}

function toggleIsNew() {
	var isNew = $("form input[name='{{form.isNew.html_name}}']").fieldValue();

	// Check which option the user selected, 'new persoon' or 'existing'
	if (isNew == 1) {
		// New. Clear search field.
		$("#searchFieldB").val("");
		// Clear persoon details form (might contain results from search field)
		resetForm("#persoonDetails");
	} else {
		// Existing. Check if search field already contains a value.  
		if (!$("#id_{{ form.idpersoonB.html_name }}").val()) {
			// Search field doesn't contain a value, clear persoon details form
			resetForm("#persoonDetails");
		}
	}

	update();
}

function selectNameB(event, ui) {
	$("{{form.idpersoonB|id}}").val(ui.item.idpersoon);
	$("{{form.txtachternaam|id}}").val(ui.item.txtachternaam);
	$("{{form.txttussenvoegsels|id}}").val(ui.item.txttussenvoegsels);
	$("{{form.txtroepnaam|id}}").val(ui.item.txtroepnaam);
	$("{{form.txtvoorletters|id}}").val(ui.item.txtvoorletters);
	$("{{form.idgeslacht|id}}").val(ui.item.idgeslacht);
	$("{{form.idlidmaatschapvorm|id}}").val(ui.item.idlidmaatschapvorm);
	update();
}

$(document).ready(function(){
	$("#searchFieldB").autocomplete({source:"/query/persoon",
									minLength: 2,
									select: selectNameB});
	
	$("#searchFieldB").focus(function() {
		loader = $("#loading");
		loader.css("position", "relative");
		loader.css("left", 4);
		loader.css("top", 4);
		$("#searchFieldB").after(loader);		
	});	

	$("form input[name='{{form.isNew.html_name}}']").click(toggleIsNew);		

	update();

});
</script>

{% block script %}
{% endblock %}

{% endblock %}

templates/KB/wizards/marry_1.html
{% extends "KB/main.html" %}

{% load customtags %}

{% block content %}

<form name="form" id="form" action="." method="post">{% csrf_token %}
<div class="box widget">
<h2>Wizard trouwen ({{ step }} van {{ step_count }})</h2>
<p>Gegevens huwelijk</p>
<div class="form_row">{{ form.dtmhuwelijksdatum|generate:"fixed" }} </div>
<div class="form_row">{{ form.dtmdatumhuwelijksbevestiging|generate:"fixed" }} {{ form.idhuwelijksgemeente|generate }} </div>
<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
{{ previous_fields|safe }}
</div>
<br class="clear"/>
<input type="submit" id="submitButton" value="Volgende">
</form>

{% endblock %}

templates/KB/wizards/marry_2.html
{% extends "KB/main.html" %}

{% load customtags %}

{% block content %}

<form name="form" id="form" action="." method="post">{% csrf_token %}
<div class="box widget">
<h2>Wizard trouwen ({{ step }} van {{ step_count }})</h2>
<p>Wie wordt hoofd van het nieuwe huishouden?</p>
<div class="form_row">
<input type="radio" name="familyHead" value="A" id="headPersoonA"/><label for="headPersoonA">{{persoonA}}</label>
<input type="radio" name="familyHead" value="B" id="headPersoonB"/><label for="headPersoonB">{{persoonB}}</label>
{{ form.gezinshoofd }}</div>

<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
{{ previous_fields|safe }}
</div>
<br class="clear"/>
<input type="submit" id="submitButton" value="Volgende">
</form>

<script type="text/javascript">

function update() {
	var familyHead = $("form input[name='familyHead']").fieldValue();

	if (familyHead == "") {
		$("#submitButton").attr("disabled", true);
	} else {
		$("form input[name='{{form.gezinshoofd.html_name}}']").val(familyHead);
		$("#submitButton").removeAttr('disabled');
	}
}

$(document).ready(function(){
	$("form input[name='familyHead']").click(update);	
	update();
});

</script>

{% endblock %}

templates/KB/wizards/marry_unknown_0.html
{% extends "KB/wizards/marry_0.html" %}

{% load customtags %}

{% block question %}
<p>Wie gaan er trouwen?</p>
{{ form.idpersoonA }}
<div class="form_row"><label class="fixed">Lid</label><input type="text" id="searchFieldA" size="30"/></div>
{% endblock %}

{% block script %}
<script type="text/javascript">

function selectNameA(event, ui) {
	$("{{form.idpersoonA|id}}").val(ui.item.idpersoon);
}

$(document).ready(function(){
	$("#searchFieldA").focus(function() {
		loader = $("#loading");
		loader.css("position", "relative");
		loader.css("left", 4);
		loader.css("top", 4);
		$("#searchFieldA").after(loader);		
	});
	$("#searchFieldA").autocomplete({source:"/query/persoon",
		minLength: 2,
		select: selectNameA});
});

</script>
{% endblock %}

templates/KB/wizards/membership_0.html
{% extends "KB/main.html" %}

{% load customtags %}

{% block content %}

<form name="form" id="form" action="." method="post">
<div class="box widget form">
<h2>Wizard lidmaatschap wijzigen ({{ step }} van {{ step_count }})</h2>
<p>Geef aan op welke manier het lidmaatschap van het huishouden
{% if is_mode_family %}
{{ gezin }}
{% else %}
{{ persoon }}
{% endif %} wijzigt.</p>
{% csrf_token %}

<div class="form_row">{{ form.idlidmaatschapstatus|generate:"fixed" }}</div>
<div id="container_dtmdatumvertrek" style="display: none">
<div class="form_row">{{ form.dtmdatumvertrek|generate:"fixed" }} {{ form.idvertrokkennaargemeente|generate }}</div>
<div class="form_row">{{ form.gastlidmaatschap|generate:"fixed" }}</div>
<div id="container_guestnotification" style="display: none; font-size: x-small"><label class="fixed"></label>Gastleden behouden altijd de actieve status<br/><br/></div>
<div class="form_row">{{ form.generateCertificate|generate:"fixed" }}</div>
</div>
<div id="container_dtmdatumonttrokken" style="display: none">
<div class="form_row">{{ form.dtmdatumonttrokken|generate:"fixed" }}</div>
</div>
<div id="container_dtmoverlijdensdatum" style="display: none">
<div class="form_row">{{ form.dtmoverlijdensdatum|generate:"fixed" }}</div>
</div>

{% if not is_mode_famiy and persoon.idgezinsrol.pk == 1 and persoon.idgezin.persoon_set.count > 1%}
<div class="form_row">{{ form.updateWholeFamily|generate:"fixed" }}</div>
{% endif %}

<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
{{ previous_fields|safe }}
</div>
<br class="clear"/>
<input type="button" id="submitButton" onClick="submitForm()" value="Volgende">
</form>

<script type="text/javascript">

function submitForm() {
	document.form.submit();
}

function updateStatus() {
	$("#container_dtmdatumvertrek").hide();
	$("#container_dtmdatumonttrokken").hide();
	$("#container_dtmoverlijdensdatum").hide();
	// Check current status
	var status = $("input[name='0-idlidmaatschapstatus']:checked").val();
	if (status == 1) {
		// Actief
		$("{{ form.dtmdatumonttrokken|id }}").val("");
		$("{{ form.dtmdatumvertrek|id }}").val("");
		$("{{ form.idvertrokkennaargemeente|id }}").val(-1);
		$("{{ form.dtmoverlijdensdatum|id }}").val("");
	}
	else if (status == 2) {
		// Vertrokken
		$("#container_dtmdatumvertrek").show();
		$("{{ form.dtmdatumonttrokken|id }}").val("");
		$("{{ form.dtmoverlijdensdatum|id }}").val("");
	} else if (status == 3) {
		// Onttrokken
		$("#container_dtmdatumonttrokken").show();
		$("{{ form.dtmdatumvertrek|id }}").val("");
		$("{{ form.idvertrokkennaargemeente|id }}").val(-1);
		$("{{ form.dtmoverlijdensdatum|id }}").val("");
	} else if (status == 4) {
		// Overleden
		$("#container_dtmoverlijdensdatum").show();
		$("{{ form.dtmdatumvertrek|id }}").val("");
		$("{{ form.idvertrokkennaargemeente|id }}").val(-1);
		$("{{ form.dtmdatumonttrokken|id }}").val("");
	}	
}

function displayGuestNotification() {
	guest = $('input:radio[name=0-gastlidmaatschap]:checked').val();
	if (guest > 0) {
		$("#container_guestnotification").show();
	} else {
		$("#container_guestnotification").hide();
	}
}

$(document).ready(function(){
	updateStatus();

});
</script>

{% endblock %}

templates/KB/wizards/membership_1.html
{% extends "KB/main.html" %}

{% load customtags %}

{% block content %}

<form name="form" id="form" action="." method="post">
<div class="box widget form">
<h2>Wizard lidmaatschap wijzigen ({{ step }} van {{ step_count }})</h2>
<p>Kies het type attestatie:</p>
{% csrf_token %}
<div class="form_row">{{ form.certificateType|generate:"fixed" }}</div>
<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
{{ previous_fields|safe }}
</div>
<br class="clear"/>
<input type="button" id="submitButton" onClick="submitForm()" value="Volgende">
</form>

<script type="text/javascript">

function submitForm() {
	document.form.submit();
}

$(document).ready(function(){

});
</script>

{% endblock %}

templates/KB/wizards/membership_2.html
{% extends "KB/main.html" %}

{% load customtags %}

{% block content %}

<form name="form" id="form" action="." method="post">
<div class="box widget form">
<h2>Wizard lidmaatschap wijzigen ({{ step }} van {{ step_count }})</h2>
<p>Attestatie:</p>
<div id="certificate">{{ form.certificate|safe }}</div>
{% csrf_token %}
<input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
{{ previous_fields|safe }}
</div>
<br class="clear"/>
<input type="button" id="submitButton" onClick="submitForm()" value="Voltooien">
</form>

<script type="text/javascript">

function submitForm() {
	document.form.submit();
}

$(document).ready(function(){

});
</script>

{% endblock %}

templates/KB/wizards/modal_redirect.html
{% extends "KB/base.html" %}

{% comment %}

Template for wizard

{% endcomment %}

{% block header %} {% endblock %}

{% block body %}

{% block content %}

<script language="javascript">
window.parent.location = "{{ redirect }}";
</script>

{% endblock %}

{% endblock %}